k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: k3d-mgmt-cluster
  currentCluster: k3d-mgmt-cluster
  clusters:
    k3d-mgmt-cluster:
      namespace:
        active: postgres-operator
        favorites:
        - postgres-operator
        - minio-operator
        - grafana
        - superset
        - minio-main-tenant
        - promtail
        - loki
        - kube-system
        - cert-manager
      view:
        active: ns
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    k8s-backend.digipolis.be:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
